import "@@@/src/ui/globals.css";
import { inter, rubik, jfs } from '@@@/src/ui/fonts';
import type { Metadata } from "next";


export const metadata: Metadata = {
    title: "My FORUM",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={rubik.className}>{children}</body>
        </html>
    );
}
